version: "2"
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
        ports:
            - "3306:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    iswa:
        build: ./iswa
        ports:
            - "5000:5000"
        depends_on:
            - mysql
